apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freshrss-db
  namespace: freshrss
spec:
  selector:
    matchLabels:
      app: freshrss-db-pod # has to match .spec.template.metadata.labels
  serviceName: "svc-db"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: freshrss-db-pod # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: freshrss-db
          image: postgres:12-alpine
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: lh-db-pvc
              mountPath: /var/lib/postgresql
          env:
            - name: POSTGRES_USER
              value: freshrss
            - name: POSTGRES_PASSWORD
              value: freshrss
            - name: POSTGRES_DB
              value: freshrss
  volumeClaimTemplates:
    - metadata:
        name: lh-db-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 2Gi
